// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type WclWindowResult = { opened: boolean; message: string }

const ARGS_MAP = { 'wcl_auth':'{"close_auth_window":[],"is_auth_window_open":[],"notify_auth_complete":[],"open_auth_window":["url"]}', 'window':'{"close":[],"is_maximized":[],"minimize":[],"toggle_maximize":[]}' }
export type Router = { "wcl_auth": {close_auth_window: () => Promise<void>, 
is_auth_window_open: () => Promise<boolean>, 
notify_auth_complete: () => Promise<void>, 
open_auth_window: (url: string) => Promise<WclWindowResult>},
"window": {close: () => Promise<void>, 
is_maximized: () => Promise<boolean>, 
minimize: () => Promise<void>, 
toggle_maximize: () => Promise<void>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
